// Auto-generated by Midnight Compact Compiler for StellarRise Governance
export enum ProposalStatus {
  Pending = 0,
  Active = 1,
  Closed = 2,
}

export enum VoteOption {
  No = 0,
  Yes = 1,
  Abstain = 2,
}

export interface ProposalMeta {
  id: string;
  titleHash: string;
  descriptionHash: string;
  creator: string;
  registrationDeadline: bigint;
  votingDeadline: bigint;
  voterEligibilityRoot: string;
  status: ProposalStatus;
  yesCount: bigint;
  noCount: bigint;
  abstainCount: bigint;
  totalVotesCast: bigint;
  createdAt: bigint;
}

export interface GovernanceContractWitnesses {
  voterSecretKey: (context: any) => Promise<Uint8Array> | Uint8Array;
  voterSalt: (context: any) => Promise<Uint8Array> | Uint8Array;
  voterEligibilityProof: (context: any, proposalId: string) => Promise<Uint8Array> | Uint8Array;
}

export interface GovernanceContractCircuits {
  createProposal(
    titleHash: Uint8Array | string,
    descriptionHash: Uint8Array | string,
    creator: Uint8Array | string,
    registrationDeadline: bigint,
    votingDeadline: bigint,
    voterEligibilityRoot: Uint8Array | string,
    currentTime: bigint
  ): Promise<string>;

  registerEligibleVoter(
    proposalId: string,
    voterCommitment: Uint8Array | string,
    currentTime: bigint
  ): Promise<boolean>;

  castPrivateVote(
    proposalId: string,
    nullifier: Uint8Array | string,
    voteChoice: VoteOption,
    currentTime: bigint
  ): Promise<boolean>;

  closeProposal(
    proposalId: string,
    currentTime: bigint
  ): Promise<ProposalMeta>;
}

export interface ContractInfo {
  contractName: string;
  compilerVersion: string;
  sourceHash: string;
  circuits: any[];
}

export declare const contractInfo: ContractInfo;
export declare class Contract {
  readonly witnesses: GovernanceContractWitnesses;
  readonly circuits: GovernanceContractCircuits;
  constructor(witnesses: GovernanceContractWitnesses);
}
export default Contract;
